name: Deploy to AWS ECR

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build Docker image from Compose
        run: |
          docker compose build

      - name: Tag Docker image
        run: |
          docker tag resume_generator-fastapi-app:latest ${{ secrets.ECR_REPOSITORY }}:latest

      - name: Push to ECR
        run: |
          docker push ${{ secrets.ECR_REPOSITORY }}:latest
