generate_cv:
  description: >
    Redacta un currículum profesional utilizando exclusivamente los siguientes datos del usuario:

    - Datos personales: {personal_data}
    - Educación: {education}
    - Experiencia laboral: {experience}
    - Habilidades: {skills}
    - Idiomas: {languages}
    - Certificaciones: {certifications}
    - Resumen profesional: {professional_summary}

    Para cada experiencia laboral:

    - Redacta 1 a 3 oraciones de éxito que resuman las principales acciones y logros.
    - Cada oración de éxito debe tener esta estructura:
      - Verbo de acción + actividad concreta + resultado o impacto (si aplica).
    - No copies literalmente los campos. Procesa la información y redacta logros como se muestra en tus ejemplos.

    No agregues contenido inventado bajo ninguna circunstancia.
    Está terminantemente prohibido inferir, completar o enriquecer la información con conocimiento externo.
    Únicamente debes reescribir y redactar profesionalmente lo que está explícitamente contenido en los datos proporcionados.
    Si falta información en una sección, simplemente omítela o deja el campo vacío.

  expected_output: >
    Un currículum redactado profesionalmente, en lenguaje natural, dividido en secciones claras:
    - Nombre completo
    - Datos de contacto
    - Resumen profesional
    - Educación
    - Experiencia profesional (con oraciones de éxito como logros)
    - Habilidades
    - Idiomas
    - Certificaciones

    No devuelvas JSON. Solo texto limpio y bien redactado.
    El contenido debe ser una versión redactada profesionalmente, pero que conserve exactamente la información entregada.
    No amplíes ni modifiques los datos.
  agent: cv_writer


structure_cv:
  description: >
    Convierte el siguiente currículum redactado en texto a un JSON con la siguiente estructura obligatoria:

    {
      fullName: string,
      contact: {
        email: string,
        phone: string,
        linkedin?: string
      },
      summary: string,
      education: [
        {
          institution: string,
          degree: string,
          startDate: string,
          endDate: string,
          description: string
        }
      ],
      experience: [
        {
          company: string,
          role: string,
          startDate: string,
          endDate: string|null,
          achievements: [string]
        }
      ],
      skills: [
        { name: string, level: string }
      ],
      languages: [
        { name: string, proficiency: string }
      ]
      certifications: [
        {
          name: string,
          institution: string,
          year: number
        }
      ]
    }

    Asegúrate de que el JSON sea válido y limpio. Solo responde con JSON.
  expected_output: >
    Un JSON limpio y estructurado con los campos mencionados. No incluyas explicaciones ni formato extra. Solo el JSON válido.
  agent: json_formatter
